---
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"  # Expose Redis on port 6379
    volumes:
      - redis_data:/data  # Persist Redis data
    networks:
      - redis_network

volumes:
  redis_data:  # Define a volume for persistent data storage

networks:
  redis_network:  # Define a network for Redis

# docker exec -it redis redis-cli
# PING
# SET test_key "Hello, Redis!"
# GET test_key