virustotal:
  api_key: ["xxxxxxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxxxxxxx"]
log:
  path: "/path/to/logs/debug.log"
  mode: ["file", "stream", "journal"]
  logger: {}
neo4j:
  uri: "neo4j://localhost:7687"
  user: ""
  password: ""