virustotal:
  api_key: ["xxxxxxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxxxxxxx"]
log:
  path: "/path/to/logs/debug.log"
  mode: ["file", "stream", "journal"]
  logger: {}
  level: "DEBUG"
neo4j:
  uri: "neo4j://localhost:7687"
  user: ""
  password: ""
sklearn:
  n_features: 1048576
features_cache:
  filename: "cached_features.pkl"
  save: false
  load: true
sampling:
  modulo: 8