log:
  path: "ml-malware-attribution/debug.log"
  mode: ["file", "stream", "journal"]
  logger: {}
  level: "DEBUG"
neo4j:
  uri: "neo4j://localhost:7687"
  user: "neo4j"
  password: "password"
sklearn:
  n_features: 1048576
features_cache:
  filename: "cached_features.pkl"
  save: true
  load: false
sampling:
  do_sampling: True
  modulo: 1
redis:
  host: "localhost"
  port: 6379
  db: 0
hnsw:
  dimension: 128
  max_elements: 1000000
model:
  default: "minhash"
samples:
  directory: "SAMPLES/APT1_MALWARE_FAMILIES/"